#############################################################################
# Makefile for building: drukknop
# Generated by qmake (2.01a) (Qt 4.8.6) on: Sat Jun 18 19:35:19 2016
# Project:  drukknop.pro
# Template: app
# Command: /usr/lib/arm-linux-gnueabihf/qt4/bin/qmake -o Makefile drukknop.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../share/qt4/mkspecs/linux-g++ -I. -I../../include/qt4/QtCore -I../../include/qt4/QtGui -I../../include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/arm-linux-gnueabihf -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/arm-linux-gnueabihf/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		drukknop.cpp moc_drukknop.cpp
OBJECTS       = main.o \
		drukknop.o \
		moc_drukknop.o
DIST          = ../../share/qt4/mkspecs/common/unix.conf \
		../../share/qt4/mkspecs/common/linux.conf \
		../../share/qt4/mkspecs/common/gcc-base.conf \
		../../share/qt4/mkspecs/common/gcc-base-unix.conf \
		../../share/qt4/mkspecs/common/g++-base.conf \
		../../share/qt4/mkspecs/common/g++-unix.conf \
		../../share/qt4/mkspecs/qconfig.pri \
		../../share/qt4/mkspecs/features/qt_functions.prf \
		../../share/qt4/mkspecs/features/qt_config.prf \
		../../share/qt4/mkspecs/features/exclusive_builds.prf \
		../../share/qt4/mkspecs/features/default_pre.prf \
		../../share/qt4/mkspecs/features/release.prf \
		../../share/qt4/mkspecs/features/default_post.prf \
		../../share/qt4/mkspecs/features/shared.prf \
		../../share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../share/qt4/mkspecs/features/warn_on.prf \
		../../share/qt4/mkspecs/features/qt.prf \
		../../share/qt4/mkspecs/features/unix/thread.prf \
		../../share/qt4/mkspecs/features/moc.prf \
		../../share/qt4/mkspecs/features/resources.prf \
		../../share/qt4/mkspecs/features/uic.prf \
		../../share/qt4/mkspecs/features/yacc.prf \
		../../share/qt4/mkspecs/features/lex.prf \
		../../share/qt4/mkspecs/features/include_source_dir.prf \
		drukknop.pro
QMAKE_TARGET  = drukknop
DESTDIR       = 
TARGET        = drukknop

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_drukknop.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: drukknop.pro  ../../share/qt4/mkspecs/linux-g++/qmake.conf ../../share/qt4/mkspecs/common/unix.conf \
		../../share/qt4/mkspecs/common/linux.conf \
		../../share/qt4/mkspecs/common/gcc-base.conf \
		../../share/qt4/mkspecs/common/gcc-base-unix.conf \
		../../share/qt4/mkspecs/common/g++-base.conf \
		../../share/qt4/mkspecs/common/g++-unix.conf \
		../../share/qt4/mkspecs/qconfig.pri \
		../../share/qt4/mkspecs/features/qt_functions.prf \
		../../share/qt4/mkspecs/features/qt_config.prf \
		../../share/qt4/mkspecs/features/exclusive_builds.prf \
		../../share/qt4/mkspecs/features/default_pre.prf \
		../../share/qt4/mkspecs/features/release.prf \
		../../share/qt4/mkspecs/features/default_post.prf \
		../../share/qt4/mkspecs/features/shared.prf \
		../../share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../share/qt4/mkspecs/features/warn_on.prf \
		../../share/qt4/mkspecs/features/qt.prf \
		../../share/qt4/mkspecs/features/unix/thread.prf \
		../../share/qt4/mkspecs/features/moc.prf \
		../../share/qt4/mkspecs/features/resources.prf \
		../../share/qt4/mkspecs/features/uic.prf \
		../../share/qt4/mkspecs/features/yacc.prf \
		../../share/qt4/mkspecs/features/lex.prf \
		../../share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/arm-linux-gnueabihf/libQtGui.prl \
		/usr/lib/arm-linux-gnueabihf/libQtCore.prl
	$(QMAKE) -o Makefile drukknop.pro
../../share/qt4/mkspecs/common/unix.conf:
../../share/qt4/mkspecs/common/linux.conf:
../../share/qt4/mkspecs/common/gcc-base.conf:
../../share/qt4/mkspecs/common/gcc-base-unix.conf:
../../share/qt4/mkspecs/common/g++-base.conf:
../../share/qt4/mkspecs/common/g++-unix.conf:
../../share/qt4/mkspecs/qconfig.pri:
../../share/qt4/mkspecs/features/qt_functions.prf:
../../share/qt4/mkspecs/features/qt_config.prf:
../../share/qt4/mkspecs/features/exclusive_builds.prf:
../../share/qt4/mkspecs/features/default_pre.prf:
../../share/qt4/mkspecs/features/release.prf:
../../share/qt4/mkspecs/features/default_post.prf:
../../share/qt4/mkspecs/features/shared.prf:
../../share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
../../share/qt4/mkspecs/features/warn_on.prf:
../../share/qt4/mkspecs/features/qt.prf:
../../share/qt4/mkspecs/features/unix/thread.prf:
../../share/qt4/mkspecs/features/moc.prf:
../../share/qt4/mkspecs/features/resources.prf:
../../share/qt4/mkspecs/features/uic.prf:
../../share/qt4/mkspecs/features/yacc.prf:
../../share/qt4/mkspecs/features/lex.prf:
../../share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/arm-linux-gnueabihf/libQtGui.prl:
/usr/lib/arm-linux-gnueabihf/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile drukknop.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/drukknop1.0.0 || $(MKDIR) .tmp/drukknop1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/drukknop1.0.0/ && $(COPY_FILE) --parents drukknop.h .tmp/drukknop1.0.0/ && $(COPY_FILE) --parents main.cpp drukknop.cpp .tmp/drukknop1.0.0/ && $(COPY_FILE) --parents drukknop.ui .tmp/drukknop1.0.0/ && (cd `dirname .tmp/drukknop1.0.0` && $(TAR) drukknop1.0.0.tar drukknop1.0.0 && $(COMPRESS) drukknop1.0.0.tar) && $(MOVE) `dirname .tmp/drukknop1.0.0`/drukknop1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/drukknop1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_drukknop.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_drukknop.cpp
moc_drukknop.cpp: drukknop.h
	/usr/lib/arm-linux-gnueabihf/qt4/bin/moc $(DEFINES) $(INCPATH) drukknop.h -o moc_drukknop.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_drukknop.h
compiler_uic_clean:
	-$(DEL_FILE) ui_drukknop.h
ui_drukknop.h: drukknop.ui
	/usr/lib/arm-linux-gnueabihf/qt4/bin/uic drukknop.ui -o ui_drukknop.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp drukknop.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

drukknop.o: drukknop.cpp drukknop.h \
		ui_drukknop.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drukknop.o drukknop.cpp

moc_drukknop.o: moc_drukknop.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_drukknop.o moc_drukknop.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

